pub const CONNECTION_EVENTS: &'static str =
  "wss://eventsub.wss.twitch.tv/ws?keepalive_timeout_seconds=30";
pub const SUBSCRIBE_URL: &str = "https://api.twitch.tv/helix/eventsub/subscriptions";
pub const VALIDATION_TOKEN_URL: &str = "https://id.twitch.tv/oauth2/validate";
pub const SEND_MESSAGE_URL: &str = "https://api.twitch.tv/helix/chat/messages";
pub const TWITCH_AUTHORISE_URL: &str = "https://id.twitch.tv/oauth2/";
pub const TWITCH_TOKEN_URL: &str = "https://id.twitch.tv/oauth2/token";
pub const TWITCH_BAN_URL: &str = "https://api.twitch.tv/helix/moderation/bans";
pub const TWITCH_DELETE_MESSAGE_URL: &str = "https://api.twitch.tv/helix/moderation/chat";
pub const GET_AD_SCHEDULE_URL: &str = "https://api.twitch.tv/helix/channels/ads";
pub const GET_CHATTERS_URL: &str = "https://api.twitch.tv/helix/chat/chatters";
